# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-28 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_collector', '0004_prospectiveuser_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectiveuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
