# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-30 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_collector', '0006_resort_main_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='thumbnail_picture',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
