# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-03 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_collector', '0008_auto_20160403_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='tld',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
