# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-03 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0006_auto_20160403_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resorts.Area'),
        ),
    ]
