# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-03 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0007_auto_20160403_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='resort',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
    ]
