# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-04 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0009_auto_20160404_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='terrain_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
