# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-04 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0010_resort_terrain_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='village_height',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
